# lightning.pytorch==2.2.0.post0
experiment_name: model4-k20-eval
seed_everything: 42

model:
  class_path: model.model4.Model4LitModule
  init_args:
    obs_len: 8
    pred_len: 12
    num_samples: 20
    noise_dim: 8
    noise_distrib: gaussian
    social_nce_loss_weight: 3
    social_nce_temperature: 0.5
    social_nce_proj_size: 16
    map_nce_loss_weight: 3
    map_nce_num_contour_points: 10
    map_nce_temperature: 0.5
    map_nce_proj_size: 16
    env_collision_loss_weight: 0.8
    encoder_arch: lstm
    encoder_weights_init: default
    encoder_hidden_size: 32
    social_module_hidden_size: 32
    social_info_type: relative
    social_module_num_layers: 2
    social_module_nhead: 4
    social_module_dim_feedforward: 64
    social_module_dropout: 0.1
    social_module_norm_first: false
    social_module_activation: relu
    environment_encoder_hidden_size: 32
    decoder_arch: lstm
    decoder_weights_init: default
    decoder_hidden_size: 64

data:
  class_path: model.datasets.dataset.SocialTrajectoryDataModule
  init_args:
    path: model/data/all
    homographies_path: model/data/homographies/eth_ucy
    coord_system: world
    frame_delta: 10
    only_visible: true
    fill_missing: false
    min_obs_len: 8
    min_pred_len: 12
    max_step_size: null
    center_scene: true
    rotate_prob: 1.0
    flip_prob: 1.0
    noise_prob: 0.2
    noise_scale: 0.05
    batch_size: 32
    num_workers: 4

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0003
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.0

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: val_ade
    mode: min
    factor: 0.5
    patience: 5
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0.0
    eps: 1.0e-08

trainer:
  accelerator: gpu
  strategy: auto
  devices: [0]
  precision: 32
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      default_hp_metric: false
  callbacks:
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_ade
      patience: 10
      verbose: false
      mode: min
  max_epochs: 250
  check_val_every_n_epoch: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
